* added thumb active and inactive icons
mohak1283/CustomSwitch pull request #23
Opened 2023-03-28 21:11 UTC by jamiecash

* added thumb active and inactive colors
* added height
* added font size
* added tooltip
* width calculated from size of child widgets
* removed most of the required values and set sensible defaults
* added padding around the widget
* General code changes to comply with latest version of flutter guidelines

2023-03-28 21:15 UTC, jamiecash commented
![image](https://user-images.githubusercontent.com/51708525/228368584-393444ab-c107-4737-9650-c0b9f40cd40f.png)
![image](https://user-images.githubusercontent.com/51708525/228368643-2ea801c5-1749-4ef5-8c41-9623754a823d.png)

2023-03-28 21:18 UTC, jamiecash commented
The following additional options along with their default values have been added:

- height = 35,
- fontSize = 16,
- activeTextColor = Colors.white,
- inactiveTextColor = Colors.white,
- activeThumbColor = Colors.white,
- inactiveThumbColor = Colors.white,
- activeTooltip = "",
- inactiveTooltip = "",
- activeThumbIcon,
- inactiveThumbIcon,

2023-03-29 05:34 UTC, mohak1283 requested changes
Minor comment

2023-03-29 05:34 UTC, mohak1283 commented on lib/custom_switch.dart
> +              message: widget.value ? widget.activeTooltip : widget.inactiveTooltip,
@jamiecash can you share a video/ss with tooltip? how's the switch looking with tooltip? All other changes looks fine to me.

2023-03-29 13:02 UTC, jamiecash commented
![image](https://user-images.githubusercontent.com/51708525/228543748-07d301c7-c0b6-40de-89fe-f35027a34586.png)
![image](https://user-images.githubusercontent.com/51708525/228543817-ae851938-2a98-45a5-87f4-ef66bea4c359.png)

2023-03-29 13:03 UTC, jamiecash commented
Added.

On Wed, 29 Mar 2023 at 06:34, Mohak Gupta ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Minor comment
> ------------------------------
>
> In lib/custom_switch.dart
> <https://github.com/mohak1283/CustomSwitch/pull/23#discussion_r1151413692>
> :
>
> > -                    child: Container(
> -                      width: 25.0,
> -                      height: 25.0,
> -                      decoration: BoxDecoration(
> -                          shape: BoxShape.circle, color: Colors.white),
> -                    ),
> +            onTap: () {
> +              if (_animationController.isCompleted) {
> +                _animationController.reverse();
> +              } else {
> +                _animationController.forward();
> +              }
> +              widget.onChanged(!widget.value);
> +            },
> +            child: Tooltip(
> +              message: widget.value ? widget.activeTooltip : widget.inactiveTooltip,
>
> @jamiecash <https://github.com/jamiecash> can you share a video/ss with
> tooltip? how's the switch looking with tooltip? All other changes looks
> fine to me.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mohak1283/CustomSwitch/pull/23#pullrequestreview-1362280669>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMKQE3JB4MZR5SH24DJLLHDW6PCYFANCNFSM6AAAAAAWLDG5BM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-03-29 17:43 UTC, mohak1283 approved these changes
LGTM, thanks for your contribution!

2023-03-29 17:44 UTC, merged

2023-03-29 17:58 UTC, jamiecash commented
Great, thanks. Could you let me know when this will next be published so
that can update my app and remove my local version.

On Wed, 29 Mar 2023 at 18:44, Mohak Gupta ***@***.***> wrote:

> Merged #23 <https://github.com/mohak1283/CustomSwitch/pull/23> into
> master.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mohak1283/CustomSwitch/pull/23#event-8879162670>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMKQE3K2LT7QRPYMS462ZR3W6RYHDANCNFSM6AAAAAAWLDG5BM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>